Nick-Max-Length: 16

Messages:
  Unknown-Command: "Неизвестная команда"
  Config-Reloaded: "Конфиг перезагружен"
  Only-Player: "Только для игроков"
  Args-Missing: "Нет нужного аргумента"
  Help: "Помощи нет."
  Max-Limit: "&4Длинна ника (Не учитывая форматирование) превышает максимальное значение!"
  No-Player: "&4Игрок не обнаружен!"
  # Для New-Name можно использовать {newName}, {oldName}, (И {player} Тот, кто изменяет ник)
  New-Name: "Вы установили ник: {newName}"
  Set-Nick: "Вы установили ник {newName} для игрока {player}"
  Set-Nick-Player-Msg: "Вам установили ник {newName}"

# Формат в кавычках не соответствует тому, что будет в будущем!
Players:
  Carde2: "&5&l"
