Messages:
  Unknown-Command: "Неизвестная команда"
  Config-Reloaded: "Конфиг перезагружен"
  Only-Player: "Только для игроков"
  Args-Missing: "Нет нужного аргумента"
  Help: "Помощи нет."

Players:
  Carde2: "{#AA00AA}&l{name}"
  taumel: "{#000000}&l{name}"
