name: Violet-NameFormat
version: '1.0.0-DEV'
main: delta.cion.Violet_NameFormat
api-version: '1.20'
authors:
  - Carde2
description: "For: Project~VIolette"
website: https://discord.gg/MEBkvJbe4P
commands:
  vionf:
    description: Main command
permissions:
  vio.color.user:
    description: Set color name for other user
    children:
      vio.color: true
  vio.nick.user:
    description: Set nickname for other user
    children:
      vio.nick: true
  vio.anvil:
    description: Color names for items in anvil
  vio.color:
    description: Set color name
  vio.nick:
    description: Set nickname
  vio.help:
    description: Get help
  vio.reset:
    description: Reset nick deco
  vio.reload:
    description: Reload config
  vio.name.format.*:
    description: All perms
    children:
      vio.anvil: true
      vio.color.user: true
      vio.nick.user: true
      vio.color: true
      vio.nick: true
      vio.help: true
      vio.reset: true
      vio.reload: true